//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int id_reserv { get; set; }
        public Nullable<System.DateTime> checkin { get; set; }
        public Nullable<System.DateTime> departure { get; set; }
        public string bookingStatus { get; set; }
        public int id_user { get; set; }
        public int roomNumber { get; set; }
    
        public virtual guest guest { get; set; }
        public virtual Room Room { get; set; }
    }
}
